apiVersion: v1
kind: Pod
metadata:
  name: pods
spec:
  containers:
    - name: pod1
      image: redis
      ports:
        - containerPort: 81
    - name: pod2 
      image: django
      ports:
        - containerPort: 82